-- Seed: Planungsstand Di 22.09.2026. Nur einmal ausführen.
do $$ begin if exists (select 1 from tasks) then raise exception 'Seed schon eingespielt – abgebrochen.'; end if; end $$;

insert into tasks (area, title, contact, priority, due, status, answer, sort) values
 ('Rahmen', 'S&G-Angebot per Mail bestätigt?', 'Hanna Michel', 'hoch', '2026-09-22', 'erledigt', 'Bestätigt. 70 Essen fix, Reduzierung nicht mehr möglich.', 0),
 ('Rahmen', 'Sind die 70 Eingeladene oder Zusagen?', 'Sponsoring-Team', 'hoch', '2026-09-22', 'erledigt', 'Einladungen – es kommen voraussichtlich weniger. Essen bleibt bei 70.', 1),
 ('Rahmen', 'Frist für Zusagen der Sponsoren (für Tisch- und Sitzplan)', 'Sponsoring-Team', 'hoch', '2026-09-24', 'offen', '', 2),
 ('Rahmen', 'Einlass 19:00 oder 19:15?', 'Vorstand', 'hoch', '2026-09-23', 'offen', '', 3),
 ('Rahmen', 'Alle Schichten 30 Min vorziehen (wie Deep Tech Dinner)?', 'Student Reps', 'hoch', '2026-09-23', 'offen', '', 4),
 ('Rahmen', 'Welcher Raum ist gebucht: großer Saal, D-006 oder beides?', 'Sara Rottenburg', 'hoch', '2026-09-23', 'offen', '', 5),
 ('Rahmen', 'Hörsaal D-001 als Neben- und Pausenraum mitbuchbar?', 'Sara Rottenburg', 'mittel', '2026-09-23', 'offen', '', 6),
 ('Rahmen', 'Budget für Licht, Deko, Blumen – Höhe und Abrechnungsweg', 'Vorstand', 'mittel', '2026-09-23', 'offen', '', 7),
 ('Rahmen', 'Wer hat Samstag bei Uneinigkeit das letzte Wort?', 'Luis Wittbrock', 'mittel', '2026-09-23', 'offen', '', 8),
 ('Rahmen', 'Versicherung über IdeaLab e.V. gedeckt?', 'Vorstand', 'niedrig', '2026-09-25', 'offen', '', 9),
 ('Rahmen', 'GEMA bei der Musik ein Thema?', 'Vorstand', 'niedrig', '2026-09-25', 'offen', '', 10),
 ('Material', 'Menüteller Ø 32 cm – wer stellt sie? Fehlen in jeder Bestellung', 'Hanna Michel', 'hoch', '2026-09-23', 'offen', '', 11),
 ('Material', 'Besteck: wo lagert es, welche Teile, wie viele?', 'Paul Läufer', 'hoch', '2026-09-23', 'offen', '', 12),
 ('Material', 'Wein-, Wasser- und Biergläser – woher?', 'Benedikt Friedrich', 'hoch', '2026-09-23', 'offen', '', 13),
 ('Material', 'Bruchreserve über die 740 Teile hinaus', 'Kai (S&G)', 'mittel', '2026-09-23', 'offen', '', 14),
 ('Material', 'Licht und Scheinwerfer reservieren (Konkurrenz Gala)', 'Technik', 'hoch', '2026-09-22', 'offen', '', 15),
 ('Material', 'Musikanlage: vorhanden, welcher Anschluss?', 'Sara Rottenburg', 'mittel', '2026-09-23', 'offen', '', 16),
 ('Material', 'Mikrofon für die Reden plus Ersatzbatterien', 'Sara Rottenburg', 'mittel', '2026-09-24', 'offen', '', 17),
 ('Material', 'Kaffee: Maschine, 45 Tassen, Untertassen, Löffel, Milch, Zucker', 'Hanna Michel', 'hoch', '2026-09-23', 'offen', '', 18),
 ('Material', 'Papiertischdecken vorhanden oder kaufen?', 'Paul Läufer', 'mittel', '2026-09-24', 'offen', '', 19),
 ('Material', 'Stofftischdecken gemeinsam mit dem Nachbarteam', 'Nachbarteam', 'mittel', '2026-09-23', 'offen', '', 20),
 ('Material', 'Holzblöcke für die Karten – wo liegen sie?', 'Paul Läufer', 'mittel', '2026-09-24', 'offen', '', 21),
 ('Material', 'Blumen und kleine Vasen – Bestand oder Einkauf?', 'IdeaLab', 'niedrig', '2026-09-25', 'offen', '', 22),
 ('Material', 'Offene Kerzen zulässig oder LED?', 'Sara Rottenburg', 'mittel', '2026-09-23', 'offen', '', 23),
 ('Material', 'Karten: Sprache vereinheitlichen, Testdruck, Stückzahl', 'Luis Wittbrock', 'mittel', '2026-09-24', 'in Arbeit', '', 24),
 ('Material', 'Tischnummern, Sitzplan-Aushang, Wegweiser', 'Marlon Osterod', 'mittel', '2026-09-25', 'offen', '', 25),
 ('Material', 'Notfallkiste packen', 'Marlon Osterod', 'niedrig', '2026-09-25', 'offen', '', 26),
 ('Anlieferung', 'S&G liefert Donnerstag 740 Teile – wer nimmt an, wo kommen sie hin?', 'Kai (S&G)', 'hoch', '2026-09-24', 'offen', '', 27),
 ('Anlieferung', 'Lagerung der 740 Teile Do–Sa sicher?', 'Sara Rottenburg', 'mittel', '2026-09-24', 'offen', '', 28),
 ('Anlieferung', 'Anlieferzeit von S&G am Samstag, je Gang', 'Kai (S&G)', 'hoch', '2026-09-23', 'offen', '', 29),
 ('Anlieferung', 'Zufahrt frei? Burgplatz wird Sa 08:00–18:00 abgebaut', 'Sara Rottenburg', 'mittel', '2026-09-25', 'offen', '', 30),
 ('Anlieferung', 'Fahrstuhl: Zugang, Schlüssel, Dauer pro Fahrt', 'Paul Läufer', 'mittel', '2026-09-25', 'offen', '', 31),
 ('Anlieferung', 'Getränke erst Samstag abstellen – wo genau, wer behält sie im Blick?', 'Benedikt Friedrich', 'mittel', '2026-09-25', 'offen', '', 32),
 ('Anlieferung', 'Wer holt das HfM-Material, womit, wann?', 'HfM', 'mittel', '2026-09-24', 'offen', '', 33),
 ('Aufbau', 'Ab wann ist der Raum Samstag zugänglich, wer schließt auf?', 'Sara Rottenburg', 'hoch', '2026-09-23', 'offen', '', 34),
 ('Aufbau', 'Zustand des Saals nach dem Deep Tech Dinner am Freitag', 'Sara Rottenburg', 'mittel', '2026-09-25', 'offen', '', 35),
 ('Aufbau', 'Saalmaße, Tischanzahl, Tischmaße, Stuhlanzahl', 'Sara Rottenburg', 'hoch', '2026-09-23', 'offen', '', 36),
 ('Aufbau', 'Tischvariante im Raumplan festlegen', 'Marlon Osterod', 'hoch', '2026-09-24', 'offen', '', 37),
 ('Aufbau', 'Lichtschaltung vorher durchprobieren (Freitag vormittags)', 'Marlon Osterod', 'mittel', '2026-09-25', 'offen', '', 38),
 ('Aufbau', 'Wo stehen Bar und Anrichtestraße? (Ausgabe bietet sich an)', 'Marlon Osterod', 'mittel', '2026-09-24', 'offen', '', 39),
 ('Aufbau', 'Set-up-Lead benennen', 'Marlon Osterod', 'mittel', '2026-09-23', 'offen', '', 40),
 ('Empfang', 'Welche Sponsoren kommen zu uns, welche zur Gala?', 'Sponsoring-Team', 'mittel', '2026-09-24', 'offen', '', 41),
 ('Empfang', 'Wer empfängt am Eingang?', 'Sponsoring-Team', 'mittel', '2026-09-25', 'offen', '', 42),
 ('Empfang', 'Tischkarten und Sitzplan', 'Sponsoring-Team', 'niedrig', '2026-09-25', 'entfällt', 'Keine Namensschilder, keine Namensliste – kein namentlicher Sitzplan.', 43),
 ('Empfang', 'Empfangsgetränk per Tablett – ja oder nein?', 'Luis Wittbrock', 'mittel', '2026-09-23', 'offen', '', 44),
 ('Empfang', 'Garderobe: wo, betreut oder unbetreut?', 'Sara Rottenburg', 'niedrig', '2026-09-25', 'offen', '', 45),
 ('Empfang', 'Dresscode für Gäste und Crew', 'Vorstand', 'mittel', '2026-09-23', 'offen', '', 46),
 ('Essen & Service', 'Ab wann braucht S&G die 4 Anrichter? 19:15 ist zu spät', 'Kai (S&G)', 'hoch', '2026-09-23', 'offen', '', 47),
 ('Essen & Service', 'Produktionshilfe Fr + Sa ab 09:00 (je 2 Pers.) besetzt?', 'Hanna Michel', 'hoch', '2026-09-23', 'offen', '', 48),
 ('Essen & Service', 'Handynummer S&G-Ansprechpartner für Samstag', 'Kai (S&G)', 'mittel', '2026-09-25', 'offen', '', 49),
 ('Essen & Service', 'Darf die Mensa-Küche genutzt werden, wer weist ein?', 'Sara Rottenburg', 'hoch', '2026-09-23', 'offen', '', 50),
 ('Essen & Service', 'Hygienebelehrung § 43 IfSG für Küchencrew nötig?', 'Kai (S&G)', 'mittel', '2026-09-23', 'offen', '', 51),
 ('Essen & Service', 'Vegane Option und Allergenliste', 'Kai (S&G)', 'niedrig', '2026-09-23', 'entfällt', 'Keine vegane Option – bewusste Entscheidung.', 52),
 ('Essen & Service', 'Teller vorwärmen möglich?', 'Kai (S&G)', 'niedrig', '2026-09-25', 'offen', '', 53),
 ('Essen & Service', 'Brot vorab auf die Tische?', 'Kai (S&G)', 'niedrig', '2026-09-23', 'offen', '', 54),
 ('Essen & Service', 'Drei Weinrundengeher aus der Service-Schicht benennen', 'Marlon Osterod', 'mittel', '2026-09-25', 'offen', '', 55),
 ('Essen & Service', 'Service-Lead und Küchen-Lead benennen', 'Marlon Osterod', 'hoch', '2026-09-23', 'offen', '', 56),
 ('Programm', 'Wer spricht, wann und wie lange?', 'Vorstand', 'mittel', '2026-09-23', 'offen', '', 57),
 ('Programm', 'Mikro Freitag testen mit der Person, die Samstag spricht', 'Marlon Osterod', 'niedrig', '2026-09-25', 'offen', '', 58),
 ('Programm', 'Jazz-Playlist, heruntergeladen, 4 h, verantwortliche Person', 'Luis Wittbrock', 'mittel', '2026-09-25', 'offen', '', 59),
 ('Programm', 'Fotograf? Dann Einwilligung klären', 'Vorstand', 'niedrig', '2026-09-25', 'offen', '', 60),
 ('Getränke', 'Bier: Fass oder Flasche? Karte verspricht Zapfhahn', 'Benedikt Friedrich', 'hoch', '2026-09-23', 'offen', '', 61),
 ('Getränke', 'Welche Mengen sind reserviert, wo stehen sie?', 'Benedikt Friedrich', 'mittel', '2026-09-23', 'offen', '', 62),
 ('Getränke', 'Kühlung: kein Kühlschrank in der Mensa', 'Benedikt Friedrich', 'mittel', '2026-09-25', 'offen', '', 63),
 ('Getränke', 'Nachschubweg über Fahrstuhl – wer läuft?', 'Marlon Osterod', 'niedrig', '2026-09-25', 'offen', '', 64),
 ('Getränke', 'Bar-Lead benennen', 'Marlon Osterod', 'mittel', '2026-09-23', 'offen', '', 65),
 ('Ende & Abbau', 'Bus-Transfer 21:30 – gilt er für unsere Gäste?', 'Vorstand', 'mittel', '2026-09-23', 'offen', '', 66),
 ('Ende & Abbau', 'Bar nach 21:30 – wer bedient, wenn Marc/Celina im Tear-down sind?', 'Marlon Osterod', 'mittel', '2026-09-25', 'offen', '', 67),
 ('Ende & Abbau', 'Entsorgung der Essensreste über das Gala-Team', 'Gala-Team', 'mittel', '2026-09-25', 'offen', '', 68),
 ('Ende & Abbau', 'Spülmaschine nutzbar? Wohin mit Geschirr danach?', 'Sara Rottenburg', 'mittel', '2026-09-25', 'offen', '', 69),
 ('Ende & Abbau', 'Raumübergabe an Hausmeister mit Protokoll', 'Marlon Osterod', 'niedrig', '2026-09-26', 'offen', '', 70),
 ('Ende & Abbau', 'Crew-Essen und Pause für die 5 mit Doppelschicht', 'Marlon Osterod', 'hoch', '2026-09-25', 'offen', '', 71),
 ('Nachbereitung', 'Material zurück an HfM', 'Marlon Osterod', 'niedrig', '2026-09-27', 'offen', '', 72),
 ('Nachbereitung', 'Belege sammeln und abrechnen', 'Luis Wittbrock', 'niedrig', '2026-09-27', 'offen', '', 73),
 ('Nachbereitung', 'Debrief mit Luis und Abgabe an IdeaLab', 'Marlon Osterod', 'niedrig', '2026-09-27', 'offen', '', 74),
 ('Nachbereitung', 'Dank an die 19 in den Gruppen', 'Marlon Osterod', 'niedrig', '2026-09-27', 'offen', '', 75);

insert into materials (category, item, quantity, source, needed_when, status, notes, sort) values
 ('Essen', '3-Gänge-Menü (Linsensalat · Maishähnchen/Planted · Panna Cotta)', '70, davon 10 veg.', 'S&G Catering', 'Sa', 'geklärt', '16,75 € netto p. P., ~1.395 € brutto', 0),
 ('Geschirr', 'Suppentasse + Unterteller', '70 + Reserve', 'S&G (740er Lieferung)', 'Do', 'bestellt', 'Null Bruchreserve über 3 Abende', 1),
 ('Geschirr', 'Whiskyglas Tumbler 0,2 l (Dessert)', '70 + Reserve', 'S&G (740er Lieferung)', 'Do', 'bestellt', '', 2),
 ('Geschirr', 'Menüteller Ø 32 cm (Hauptgang)', '77', 'ungeklärt', 'Fr', 'offen', 'Fehlt in jeder Bestellung', 3),
 ('Geschirr', 'Besteck (Vorspeise, Hauptgang, Dessertlöffel)', '~390 Teile', 'HfM', 'Fr', 'offen', '', 4),
 ('Gläser', 'Wein-, Wasser-, Biergläser', '~242', 'ungeklärt', 'Fr', 'offen', '', 5),
 ('Tisch', 'Stofftischdecken', '1 je Tisch + 2', 'Nachbarteam', 'Fr', 'offen', 'Maße erst nach Saalmaßen', 6),
 ('Tisch', 'Papiertischdecken / Molton', 'nach Tischzahl', 'IdeaLab-Bestand oder Metro', 'Fr', 'offen', '', 7),
 ('Tisch', 'Stoffservietten', '80', 'ungeklärt', 'Fr', 'offen', '', 8),
 ('Deko', 'Holzblöcke für Karten', '1 je Tisch', 'IdeaLab-Bestand', 'Fr', 'offen', 'Paul: „richtig wichtig“ – suchen', 9),
 ('Deko', 'Blumen und kleine Vasen (max. 25 cm hoch)', '1 je Tisch', 'Bestand oder Einkauf', 'Sa', 'offen', '', 10),
 ('Deko', 'LED-Kerzen / Windlichter', '2–3 je Tisch', 'Einkauf', 'Fr', 'offen', 'Brandschutz: offene Kerzen klären', 11),
 ('Deko', 'Lichterketten warmweiß', '3–4', 'Einkauf / Bestand', 'Fr', 'offen', '', 12),
 ('Druck', 'Menü- und Getränkekarten', '~35', 'Druck (Luis)', 'Fr', 'angefragt', 'Testdruck vorher', 13),
 ('Druck', 'Tischnummern-Aufsteller', '1 je Tisch', 'Druck', 'Fr', 'offen', '', 14),
 ('Technik', 'Uplights / Scheinwerfer', '6–10', 'Technik (Konkurrenz Gala)', 'Fr', 'offen', 'Heute reservieren', 15),
 ('Technik', 'Musikanlage + Kabel + Adapter', '1', 'Mensa / Technik', 'Fr', 'offen', '', 16),
 ('Technik', 'Mikrofon + Ersatzbatterien', '1–2', 'Technik', 'Fr', 'offen', '', 17),
 ('Getränke', 'Wein weiß / rot', '~30–36 Fl.', 'Benedikt (zentral)', 'Sa', 'offen', 'Kommission anfragen', 18),
 ('Getränke', 'Wasser still / spritzig', '~90 Fl.', 'Benedikt (zentral)', 'Sa', 'offen', '', 19),
 ('Getränke', 'Bier', '1–2 Kästen oder Fass', 'Benedikt (zentral)', 'Sa', 'offen', 'Karte verspricht „on tap“', 20),
 ('Getränke', 'Kaffee, Tassen, Milch, Zucker', '~45 Tassen', 'ungeklärt', 'Sa', 'offen', '', 21),
 ('Getränke', 'Eis, Eisboxen, Weinkühler', '~5 kg Eis', 'Einkauf', 'Sa', 'offen', 'Kein Kühlschrank vor Ort', 22),
 ('Kleinkram', 'Korkenzieher / Kellnermesser', '4', 'Einkauf', 'Sa', 'offen', '', 23),
 ('Kleinkram', 'Flaschenöffner', '3', 'Einkauf', 'Sa', 'offen', '', 24),
 ('Kleinkram', 'Servierttücher', '10', 'Bestand', 'Sa', 'offen', '', 25),
 ('Kleinkram', 'Kehrblech, Besen, Müllbeutel, Leergutkisten', 'je 2', 'Mensa / Einkauf', 'Sa', 'offen', '', 26),
 ('Kleinkram', 'Notfallkiste (Tape, Kabelbinder, Pflaster, Stifte, Ladekabel)', '1', 'selbst packen', 'Sa', 'offen', '', 27),
 ('Crew', 'Crew-Verpflegung (Brötchen / Reste) + Wasser', '19 Pers.', 'ungeklärt', 'Sa', 'offen', '', 28);

insert into contacts (name, role, org, responsible_for, phone, sort) values
 ('Marlon Osterod', 'Organisation, Shift Manager aller 5 Schichten', 'IdeaLab (Anwärter)', 'Gesamtleitung', '', 0),
 ('Luis Wittbrock', 'Co-Organisator', 'IdeaLab (Anwärter)', 'Speise- und Getränkekarten', '', 1),
 ('Hanna Michel', 'IdeaLab e.V.', 'IdeaLab e.V.', 'Schnittstelle zu S&G, Bestellungen, Budget', '', 2),
 ('Kai (S&G)', 'Caterer', 'S&G Catering GmbH, Koblenz', 'Menü, Anlieferung, Anrichten', '0261 / 44400', 3),
 ('Sara Rottenburg', 'WHU Eventmanagement', 'WHU', 'Raum, Zugang, Licht, Küche, Technik', '', 4),
 ('Benedikt Friedrich', 'Getränke', 'IdeaLab', 'Getränke, zentrale Getränkeorga', '', 5),
 ('Paul Läufer', 'Sponsor Dinner Vorjahr', 'IdeaLab', 'Erfahrung, Material, Fahrstuhl, Lagerung', '', 6),
 ('HfM', 'Material', 'HfM', 'Geschirr und Aufbaumaterial', '', 7),
 ('Student Reps', 'Schichtplanung', 'IdeaLab', 'Schichtzeiten und Besetzung', '', 8),
 ('Sponsoring-Team', 'Gäste', 'IdeaLab', 'Gäste- und Sponsorenkontakt', '', 9),
 ('Vorstand', 'Entscheidungen', 'IdeaLab e.V.', 'Programm, Redner, Budget, Einlasszeit', '', 10),
 ('Technik', 'Licht & Ton', 'IdeaLab / WHU', 'Scheinwerfer, Uplights, Mikro', '', 11),
 ('Nachbarteam', 'Deep Tech Dinner', 'IdeaLab', 'Gemeinsame Tischwäsche', '', 12),
 ('Gala-Team', 'Gala Dinner Stadthalle', 'IdeaLab', 'Entsorgung, Material-Konkurrenz', '', 13);

insert into schedule (kind, day, start_time, end_time, phase, title, who, flagged) values
 ('abend', '2026-09-26', '17:30', '', 'Vorbereitung', 'Vor Ort, Schlüssel und Raumzustand prüfen', 'Marlon', false),
 ('abend', '2026-09-26', '18:00', '', 'Set-up', 'Set-up-Briefing, Check-in der 5 Personen', 'Marlon', false),
 ('abend', '2026-09-26', '18:00', '18:10', 'Set-up', 'Raumcheck, Licht und Technik testen', 'Set-up-Crew', false),
 ('abend', '2026-09-26', '18:10', '18:35', 'Set-up', 'Tische stellen nach Raumplan', 'Set-up-Crew', false),
 ('abend', '2026-09-26', '18:35', '18:50', 'Set-up', 'Tischwäsche auflegen, Molton drunter', 'Set-up-Crew', false),
 ('abend', '2026-09-26', '18:45', '', 'Küche', 'Anrichten beginnt – Schicht startet laut Plan erst 19:15', 'Küche (4)', true),
 ('abend', '2026-09-26', '18:50', '19:05', 'Set-up', 'Eindecken: Teller, Besteck, Gläser, Servietten', 'Set-up-Crew', false),
 ('abend', '2026-09-26', '19:05', '19:10', 'Set-up', 'Deko, Menükarten, Tischnummern', 'Set-up-Crew', false),
 ('abend', '2026-09-26', '19:10', '', 'Set-up', 'Musik an, Licht auf Abendstimmung', 'Marlon', false),
 ('abend', '2026-09-26', '19:10', '19:15', 'Übergabe', 'Kurzbriefing aller 19 (nicht auf 19:15 – kollidiert mit Einlass)', 'Marlon', true),
 ('abend', '2026-09-26', '19:15', '19:30', 'Empfang', 'Einlass, Tablett-Service Wasser und Wein', '2 Service + 2 Set-up', false),
 ('abend', '2026-09-26', '19:30', '', 'Empfang', 'Gäste nehmen Platz, leere Gedecke abräumen', 'Service', false),
 ('abend', '2026-09-26', '19:35', '19:40', 'Programm', 'Begrüßung (3–5 Min), Musik aus', 'IdeaLab', false),
 ('abend', '2026-09-26', '19:45', '', 'Service', 'Vorspeise Welle 1, dann Welle 2', 'Küche + Service', false),
 ('abend', '2026-09-26', '19:50', '', 'Service', 'Erste Weinrunde', '3 aus Service', false),
 ('abend', '2026-09-26', '20:05', '', 'Service', 'Vorspeise abräumen', 'Service', false),
 ('abend', '2026-09-26', '20:12', '', 'Service', 'Hauptgang Welle 1 und 2 – kritischster Moment', 'Küche + Service', true),
 ('abend', '2026-09-26', '20:18', '', 'Service', 'Weinrunde', '3 aus Service', false),
 ('abend', '2026-09-26', '20:45', '', 'Service', 'Hauptgang abräumen', 'Service', false),
 ('abend', '2026-09-26', '20:50', '', 'Programm', 'Sponsorenwort, zweite Rede, Musik aus', 'IdeaLab', false),
 ('abend', '2026-09-26', '21:00', '', 'Service', 'Dessert einsetzen, Kaffee ausschenken', 'Küche + Service', false),
 ('abend', '2026-09-26', '21:05', '', 'Crew', 'Essen und Kurzpause für die 5 mit Doppelschicht', 'Marlon', true),
 ('abend', '2026-09-26', '21:20', '', 'Service', 'Dessert abräumen, Bar bleibt offen', 'Service', false),
 ('abend', '2026-09-26', '21:30', '', 'Transfer', 'Bus-Transfer – gilt er für unsere Gäste?', 'offen', true),
 ('abend', '2026-09-26', '21:30', '22:00', 'Abbau', 'Tear-down beginnt, leise solange Gäste da sind', 'Tear-down (5)', false),
 ('abend', '2026-09-26', '22:00', '22:30', 'Abbau', 'Geschirr spülen und sortieren, Wäsche einsammeln', 'Tear-down', false),
 ('abend', '2026-09-26', '22:30', '22:50', 'Abbau', 'Tische und Stühle zurück, Leergut raus', 'Tear-down', false),
 ('abend', '2026-09-26', '22:50', '23:00', 'Abbau', 'Endkontrolle, Übergabe an den Hausmeister', 'Marlon', false),
 ('woche', '2026-09-22', '', '', '', 'Anfragen raus, WhatsApp-Gruppen anlegen, Leads benennen', '', false),
 ('woche', '2026-09-23', '', '', '', 'Mensa-Termin mit Sara, Tischstellung, Karten final, Bestellungen fixieren', '', false),
 ('woche', '2026-09-24', '', '', '', 'S&G liefert 740 Geschirrteile, Menükarten in Druck, Crew-Briefing raus', '', false),
 ('woche', '2026-09-25', '', '', '', 'Vormittags Raum ansehen und messen, Material hoch, Technik testen, Einkauf. Abends Deep Tech Dinner im selben Raum', '', false),
 ('woche', '2026-09-26', '', '', '', '17:30 Aufbau, 19:00 Event, 23:00 Ende', '', false),
 ('woche', '2026-09-27', '', '', '', 'Rückgabe an HfM, Wäsche, Abrechnung, Debrief', '', false),
 ('deadline', '2026-09-23', '12:00', '', '', 'Menü, Personenzahl, Getränkebestellung, Tischstellung fix', '', true),
 ('deadline', '2026-09-24', '12:00', '', '', 'Deko und Einkaufsliste fix', '', true),
 ('deadline', '2026-09-25', '12:00', '', '', 'Raumplan, Minutenplan und Crew-Einteilung fix', '', true),
 ('deadline', '2026-09-25', '18:00', '', '', 'Änderungsstopp', '', true);

insert into shifts (id, label, start_time, end_time, whatsapp, sort) values
 ('setup', 'Set-up', '18:00', '19:30', 'SD Set-up', 1),
 ('service', 'Service', '19:15', '21:30', 'SD Service', 2),
 ('bar', 'Bar', '19:15', '21:30', 'SD Bar & Küche', 3),
 ('kueche', 'Küche', '19:15', '21:30', 'SD Bar & Küche', 4),
 ('teardown', 'Tear-down', '21:30', '23:00', 'SD Tear-down', 5);

insert into crew (name, shifts) values
 ('Laura Stehlin', array['setup']::text[]),
 ('Alexander Joachim', array['setup']::text[]),
 ('Nicolas Boisseree', array['setup']::text[]),
 ('Hendrik Rei', array['setup']::text[]),
 ('David Boehm', array['setup']::text[]),
 ('Johanna Muehlbauer', array['service','teardown']::text[]),
 ('Flore Glaesener', array['service']::text[]),
 ('Sophie Mril', array['service','teardown']::text[]),
 ('Kristina Bartelt', array['service','teardown']::text[]),
 ('Jette Kasper', array['service']::text[]),
 ('Adele Bhandari', array['service']::text[]),
 ('Alexis Wesemann', array['service']::text[]),
 ('Constantin Oberbracht', array['service']::text[]),
 ('Marc Steinhaeuser', array['bar','teardown']::text[]),
 ('Celina Clausen', array['bar','teardown']::text[]),
 ('Emilie Song', array['kueche']::text[]),
 ('Moritz Hoffmann', array['kueche']::text[]),
 ('Hussein Abdullah', array['kueche']::text[]),
 ('Chiara Giesting', array['kueche']::text[]);
